---
title: "hutchins-theme"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{hutchins-theme}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(gghutchins)
library('tidyverse')
library('ggthemes')
```

```{r}
p <- ggplot(iris, aes(x = Petal.Width, y = Petal.Length, color = Species)) + 
    geom_point() +
    labs(title = 'Branding your ggplot Graphs',
         subtitle = 'Simple tweaks you can use to boost the impact of your graphs today',
         x = 'This axis title intentionally left blank',
         y = 'This axis title intentionally left blank',
         caption = 'michaeltoth.me / @michael_toth')
```

```{r}
logo <- hutchins_logo()
p +
  scale_color_manual(name = '',
                            labels = c('Black', 'Red', 'Gray'),
                            values = c('#000000', '#EC0108', '#ACAEAD')) +
    theme_hc() +
    theme(plot.title = element_text(color = "#EC0108"),
          plot.caption = element_text(color = "#EC0108", face = 'bold')) +
  grid::grid.raster(logo, x = 0.07, y = 0.03, just = c('left', 'bottom'), width = unit(1, 'inches'))
```

